=== Guillemwos/DAW1A-GuillemCastano/M04_Lenguage_Marcas/XSD/Agenda.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="agenda">

    <xs:complexType>
      <xs:sequence>
          <xs:element name="propietari">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="nom" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="1"/>
              </xs:sequence>
            </xs:complexType>        
        </xs:element>

        <xs:element name="contactes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="contacte" maxOccurs="unbounded">
                <xs:complexType >
                  <xs:sequence>
                    <xs:element name="nom" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="telefon" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="000000001" />
                          <xs:maxInclusive value="999999999" />
                          <xs:pattern value="[0-9]{9}" />
                        </xs:restriction>
                      </xs:simpleType>
                     </xs:element>
                     <xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>        
              </xs:element>      
            </xs:sequence>  
          </xs:complexType>        
        </xs:element>        
      </xs:sequence>
      <xs:attribute name="any" type="xs:integer" use="required"/>

    </xs:complexType>    
  </xs:element>

</xs:schema>

=== Guillemwos/DAW1A-GuillemCastano/M04_Lenguage_Marcas/XSD/Agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda any="2013" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Agenda.xsd">
    <propietari>
          <nom>Eloy Albiach Forner</nom>
          <email>eloy.albiachgmail.com</email>
    </propietari>
    <contactes>
        <contacte>
            <nom>Anna Monson√≠s</nom>
            <telefon>633124751</telefon>
            <email>annamongmail.com</email>
        </contacte>
        <contacte>
            <nom>Jordi Ventura</nom>
            <telefon>934152237</telefon>
            <email>jordivxtec.cat</email>
        </contacte>
    </contactes>
</agenda>
