=== Guillemwos/DAW1A-GuillemCastano/M04_Lenguage_Marcas/XSD/Sociedad.xsd
<!-- He posat dues versions del xsd perquè el validador em donava respostes 
contradictòries.
En un em donava el xsd com a correcte i en un altre em deia que havia de treure els "/"
a mesura que anava tancant elements.-->

<!--XSD 1-->

<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Sociedad">
    <xs:attribute name="N_Sociedad" type="xs:string" use="required" value="[0-9]{3}[A-Z]{1}" length="4"/>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string" />
          <xs:simpleType>
            <xs:restriction>
              <xs:minLength value="1"/>
              <xs:maxLength value="15"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Anno_Fundacion" type="xs:year" />
          <xs:simpleType>
            <xs:restriction value="xs:year">
              <xs:minInclusive value="1500"/>
              <xs:maxInclusive value="2050"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Presidente">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Nombre" type="xs:string" />
                <xs:simpleType>
                  <xs:restriction>
                    <xs:minLength value="1"/>
                    <xs:maxLength value="20"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Apellidos" type="xs:string" />
                <xs:simpleType>
                  <xs:restriction>
                    <xs:minLength value="1"/>
                    <xs:maxLength value="30"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="n_socio" type="xs:unsignedByte" use="required" />
            <xs:attribute name="nif" type="xs:string" use="required" value="[0-9]{8}[A-Za-z]{1}" length="9"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="Socios">
          <xs:attribute name="Cantidad" type="xs:integer" use="required" />
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="150"/>
          </xs:attribute>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Socio">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Nombre" type="xs:string" />
                      <xs:simpleType>
                        <xs:restriction>
                          <xs:minLength value="1"/>
                          <xs:maxLength value="20"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Apellidos" type="xs:string" />
                      <xs:simpleType>
                        <xs:restriction>
                          <xs:minLength value="1"/>
                          <xs:maxLength value="30"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="n_socio" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="nif" type="xs:string" use="required" value="[0-9]{8}[A-Za-z]{1}" length="9"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Cantidad" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="N_Sociedad" type="xs:unsignedByte" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>


<!--XSD 2-->


<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Sociedad">
    <xs:attribute name="N_Sociedad" type="xs:string" use="required" value="[0-9]{3}[A-Z]{1}" length="4"/>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string" />
          <xs:simpleType>
            <xs:restriction>
              <xs:minLength value="1"/>
              <xs:maxLength value="15"/>
            </xs:restriction>
          </xs:simpleType>
        <xs:element>
        <xs:element name="Anno_Fundacion" type="xs:year" />
          <xs:simpleType>
            <xs:restriction value="xs:year">
              <xs:minInclusive value="1500"/>
              <xs:maxInclusive value="2050"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Presidente">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Nombre" type="xs:string" />
                <xs:simpleType>
                  <xs:restriction>
                    <xs:minLength value="1"/>
                    <xs:maxLength value="20"/>
                  </xs:restriction>
                </xs:simpleType>
              <xs:element>
              <xs:element name="Apellidos" type="xs:string" />
                <xs:simpleType>
                  <xs:restriction>
                    <xs:minLength value="1"/>
                    <xs:maxLength value="30"/>
                  </xs:restriction>
                </xs:simpleType>
              <xs:element>
            <xs:sequence>
            <xs:attribute name="n_socio" type="xs:unsignedByte" use="required" />
            <xs:attribute name="nif" type="xs:string" use="required" value="[0-9]{8}[A-Za-z]{1}" length="9"/>
          <xs:complexType>
        <xs:element>
        <xs:element name="Socios">
          <xs:attribute name="Cantidad" type="xs:integer" use="required" />
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="150"/>
          </xs:attribute>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Socio">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Nombre" type="xs:string" />
                      <xs:simpleType>
                        <xs:restriction>
                          <xs:minLength value="1"/>
                          <xs:maxLength value="20"/>
                        <xs:restriction>
                      <xs:simpleType>
                    <xs:element>
                    <xs:element name="Apellidos" type="xs:string" />
                      <xs:simpleType>
                        <xs:restriction>
                          <xs:minLength value="1"/>
                          <xs:maxLength value="30"/>
                        <xs:restriction>
                      <xs:simpleType>
                    <xs:element>
                  <xs:sequence>
                  <xs:attribute name="n_socio" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="nif" type="xs:string" use="required" value="[0-9]{8}[A-Za-z]{1}" length="9"/>
                <xs:complexType>
              <xs:element>
            <xs:sequence>
            <xs:attribute name="Cantidad" type="xs:unsignedByte" use="required" />
          <xs:complexType>
        <xs:element>
      <xs:sequence>
      <xs:attribute name="N_Sociedad" type="xs:unsignedByte" use="required" />
    <xs:complexType>
  <xs:element>
<xs:schema>

=== Guillemwos/DAW1A-GuillemCastano/M04_Lenguage_Marcas/XSD/Sociedad.xml
<?xml version="1.0" encoding="UTF-8"?>
<Sociedad N_Sociedad="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Sociedad.xsd">
    <Nombre>Sociedad 1</Nombre>
    <Anno_Fundacion>1996</Anno_Fundacion>
    <Presidente n_socio = "0" nif = "34591283R">
        <Nombre>Antonio</Nombre>
        <Apellidos>Perez Lopez</Apellidos>
    </Presidente>
    <Socios Cantidad = "2">
        <Socio n_socio = "1" nif = "61039481L">
            <Nombre>Manolo</Nombre>
            <Apellidos>Galvan Vazquez</Apellidos>
        </Socio>
        <Socio n_socio = "2" nif = "58293026M">
            <Nombre>Marta</Nombre>
            <Apellidos>Carro Moyano</Apellidos>
        </Socio>
    </Socios>
</Sociedad>
